openapi: 3.0.0
info:
  title: Minesweeper API
  description: Deviget code challenge
  version: 0.0.1

servers:
  - url: http://minesweeper.com/v1
    description: Main server

paths:
  /ping:
    get:
      summary: Just pings the server for availability
      description: Ping & Pong
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
                example: PONG
  /users:
    post:
      summary: Creates a new user
      description: If you're new to the system, start here
      responses:
        '201':
          description: A JSON object describing the new user properties
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /games:
    post:
      summary: Creates a new game
      description: With your user, you can create new games
      security:
        - ApiKeyAuth: []
      requestBody:
        description: Game parameters
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GameCreationDto'
      responses:
        '401':
          description: Authorization information is missing or invalid.

        '400':
          description: User error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '201':
          description: A JSON object describing the new game properties
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

  schemas:
    GameCreationDto:
      type: object
      properties:
        width:
          type: integer
          description: Board width
          minimum: 8
          maximum: 64
        height:
          type: integer
          description: Board height
          minimum: 8
          maximum: 64
        mines:
          type: integer
          description: How many mines to setup in the board. Limited to 50% of the board.
          minimum: 1
    Error:
      type: object
      properties:
        message:
          type: string
          description: The error message
    User:
      type: object
      properties:
        id:
          type: integer
          description: The user ID.
        api_key:
          type: string
          description: The api key for this user.
    Game:
      type: object
      properties:
        id:
          type: integer
          description: The game ID.
        width:
          type: integer
          description: Board width
        height:
          type: integer
          description: Board height
        mines:
          type: integer
          description: How many mines to setup in the board. Limited to 50% of the board.
